---
- name: Create directory
  ansible.builtin.file:
    path: "{{ cni_config_dir }}"
    mode: 0755
    state: directory
    owner: "{{ cni_owner }}"
    group: "{{ cni_group }}"

- name: Create configuration files
  ansible.builtin.template:
    src: config.j2
    dest: "{{ cni_config_dir }}/{{ item.key }}"
    mode: 0644
    owner: "{{ cni_owner }}"
    group: "{{ cni_group }}"
  with_items:
    - "{{ cni_configs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
