---
namespace: hostinger
name: fireactions
repository: https://github.com/hostinger/ansible-collection-fireactions
version: 0.0.1
readme: README.md
authors:
  - konradasb
description: Ansible collection for deploying Fireactions and required dependencies
license:
  - MIT
dependencies:
  community.general: ">=4.5.0"
tags:
  - fireactions
