---
containerd_version: 1.7.0
containerd_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-{{ containerd_arch }}.tar.gz
containerd_install_dir: /opt/containerd/{{ containerd_version }}
containerd_owner: root
containerd_group: root
containerd_arch: amd64
containerd_service_state: started
containerd_binaries:
  - containerd
  - ctr
containerd_config_dir: /etc/containerd
containerd_config: |
  version = 2

  root      = "/var/lib/containerd"
  imports   = []
  state     = "/run/containerd"
  oom_score = 0

  [grpc]
    address = "/run/containerd/containerd.sock"
    uid     = 0
    gid     = 0
