---
galaxy_info:
  role_name: client
  author: hostinger
  description: Ansible role for installing Fireactions client
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - fireactions

dependencies:
  - role: containerd
  - role: cni_plugins
    vars:
      cni_plugins_binaries:
      - bridge
      - host-local
      - firewall
      - tap
  - role: cni
    vars:
      cni_configs:
        10-fireactions.conf: "{{ fireactions_client_cni_network_config }}"
  - role: sysctl
    vars:
      sysctl_d:
        10-fireactions:
        - name: net.ipv4.ip_forward
          value: 1
  - role: firecracker
    vars:
      firecracker_version: 1.4.1
