---
galaxy_info:
  role_name: client
  author: hostinger
  description: Ansible role for installing Fireactions client
  license: license (MIT)
  min_ansible_version: "2.10"
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
  - fireactions

dependencies:
  - role: hostinger.core.containerd
    vars:
      containerd_arch: "{{ fireactions_client_arch }}"
    when:
    - fireactions_client_install_containerd | default(true)
  - role: hostinger.core.cni_plugins
    vars:
      cni_plugins_arch: "{{ fireactions_client_arch }}"
      cni_plugins_binaries:
      - bridge
      - host-local
      - firewall
      - tap
    when:
    - fireactions_client_install_cni_plugins | default(true)
  - role: hostinger.core.cni
    vars:
      cni_configs:
        10-fireactions.conf: "{{ fireactions_client_cni_network_config }}"
    when:
    - fireactions_client_install_cni | default(true)
  - role: hostinger.core.sysctl
    vars:
      sysctl_d:
        10-fireactions:
        - name: net.ipv4.ip_forward
          value: 1
  - role: firecracker
    vars:
      firecracker_arch: "{% if fireactions_client_arch == 'amd64' %}x86_64{% else %}aarch64{% endif %}"
      firecracker_version: 1.4.1
    when:
    - fireactions_client_install_firecracker | default(true)
