---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: default
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    pre_build_image: true
    privileged: true
    platform: amd64
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
